### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by timhartmann**
Take a look at the commits. I restructure the assets-folder and including scss-components as dependency for faster development with sass. Installing dependencies via bower (assets/components), structure scss-files in modules, states, layouts and base.

### CODE REVIEW

**Comment by cburgdorf** [comment]
I like those changes. Can you just make sure to update the PR to make it possible to switch between minified and unminified css. I'm happy to merge it then. Thanks for your help!

**Comment by timhartmann** [comment]
Why do you need a unminifed version for development? What is the default szenario?

You include application.css in your template, develop some scss and get an unminified css. When you go live you want to have the minified css, but you must change the url in your template to application.min.css. If you know develop it you will never get a newer version, because in development-mode you get the normal application.css. I hope you understand what I mean.

Include application.css in your template and make a minified version as default ;)

For the different folders like _base, _modules etc. you should take a look at SMACSS:
http://smacss.com/

**Comment by cburgdorf** [comment]
An unminified version is just a little bit more convenient to work with from the browser. What you describe can be overcome by simply just using **one** name: `application.css`. Whether you use `sass:dev` or `sass:production` won't matter, both will create a file called `application.css`. This way you don't have to change the template and can easily switch between minified and unminified versions.

**Comment by cburgdorf** [comment]
Thanks! Landed! I slightly changed commits to not have one commit removing the `scss:dist` and another one adding it again.

**Pull request closed without merging**
